title:   Olugbenga Olatunji
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > Passionate Business Intelligence Data Analyst with a proven track record in transforming complex datasets into actionable insights. Expertise in SQL, Python, Tableau, and Power BI. Skilled in customer segmentation, campaign analysis, and KPI reporting. Dedicated to driving data-driven decisions and fostering growth through mentorship.
  <br><br>
  Results-driven data analyst, product owner and business system analyst with experiences and a track record of delivering innovative technical solutions that enhance the experience of both customers and analytic professionals. Proficient in SQL, Python, and Power BI, with a validated competence to automate dashboards, streamline processes, and provide tactical direction to stakeholders using easy-to-understand language. Skilled in analyzing behavioral data, identifying business gaps, and developing solutions that meet the needs of both internal and external stakeholders.
  <br><br>
  <a href="https://www.linkedin.com/in/olugbenga-olatunji-mba/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/olugbenga.joseph.olatunji">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/olugbengaolatunji/Portfolio-OLUGBENGA-OLATUNJI-0df332aa16a14ab0acf780b492e75c2b">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal   
 
