title:   Olugbenga Olatunji
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > Passionate Business Intelligence Data Analyst with a proven track record in transforming complex datasets into actionable insights. Expertise in SQL, Python, Tableau, and Power BI. Skilled in customer segmentation, campaign analysis, and KPI reporting. Dedicated to driving data-driven decisions and fostering growth through mentorship.
  <br><br>
  I am dedicated to achieving impactful outcomes. My background encompasses roles as a data analyst, product owner, and business system analyst, marked by a history of conceiving inventive technical solutions that elevate customer and analytical professional satisfaction. My expertise spans SQL, Python, and Power BI, and I possess a proven ability to automate dashboards, optimize workflows, and offer strategic guidance to stakeholders in clear and accessible terms. My proficiency lies in dissecting behavioral data, pinpointing operational deficiencies, and crafting effective solutions that cater to the distinct requirements of both internal and external stakeholders.
  <br><br>
  <a href="https://www.linkedin.com/in/olugbenga-olatunji-mba/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/olugbenga.joseph.olatunji">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/olugbengaolatunji/Portfolio-OLUGBENGA-OLATUNJI-0df332aa16a14ab0acf780b492e75c2b">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal   
 
